# spring:
#   datasource:
#     url: jdbc:h2:mem:mydb
#     username: sa
#     password: password
#     driverClassName: org.h2.Driver
#   jpa:
#     database-platform: org.hibernate.dialect.H2Dialect
#     defer-datasource-initialization: true
#   h2:
#     console:
#       path: /h2-console
#       settings.trace: false
#       settings.web-allow-others: 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TestDb
    username: root
    password: Naveen@270
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        # generate_statistics: true
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:templates/userCrud/
    # prefix: classpath:templates/alok/
logging:
  file: logs/application-debug.log
  pattern:
    console: "%date  %highlight(%-5level) [%12.12thread] %yellow(%-40.40logger{40}) : %msg %n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: INFO
